/**
 * Pre-built timer design templates.
 * Each template defines a curated color combination that merchants
 * can apply with one click, then customize further.
 */

export const PRODUCT_TIMER_TEMPLATES = [
  {
    id: "urgency-red",
    name: "Urgency Red",
    description: "Bold red badge",
    productStyle: "badge",
    textColor: "#ffffff",
    accentColor: "#ffffff",
    bgColor: "#dc2626",
    labelText: "Ends in",
    barIcon: "🔥",
  },
  {
    id: "minimal-dark",
    name: "Minimal Dark",
    description: "Clean text-only",
    productStyle: "minimal",
    textColor: "#1a1a1a",
    accentColor: "#dc2626",
    bgColor: "",
    labelText: "Sale ends in",
    barIcon: "",
  },
  {
    id: "card-clean",
    name: "Card Clean",
    description: "Bordered card style",
    productStyle: "card",
    textColor: "#374151",
    accentColor: "#2563eb",
    bgColor: "#f0f9ff",
    labelText: "Limited time offer",
    barIcon: "⏰",
  },
  {
    id: "floating-alert",
    name: "Floating Alert",
    description: "Sticky attention-grab",
    productStyle: "floating",
    textColor: "#92400e",
    accentColor: "#d97706",
    bgColor: "#fffbeb",
    labelText: "Don't miss out!",
    barIcon: "⚡",
  },
  {
    id: "banner-elegant",
    name: "Elegant Banner",
    description: "Full-width with accent",
    productStyle: "banner",
    textColor: "#1e293b",
    accentColor: "#7c3aed",
    bgColor: "#f5f3ff",
    labelText: "Exclusive deal ends in",
    barIcon: "",
  },
];

export const TIMER_TEMPLATES = [
  {
    id: "classic",
    name: "Classic Green",
    description: "Clean and professional",
    barColor: "#288d40",
    textColor: "#ffffff",
    buttonBgColor: "#ffffff",
    buttonTextColor: "#1a1a1a",
  },
  {
    id: "urgent-red",
    name: "Urgent Red",
    description: "Maximum urgency",
    barColor: "#dc2626",
    textColor: "#ffffff",
    buttonBgColor: "#ffffff",
    buttonTextColor: "#dc2626",
  },
  {
    id: "elegant-dark",
    name: "Elegant Dark",
    description: "Premium and luxurious",
    barColor: "#1a1a2e",
    textColor: "#e2b96f",
    buttonBgColor: "#e2b96f",
    buttonTextColor: "#1a1a2e",
  },
  {
    id: "bfcm",
    name: "Black Friday",
    description: "Bold BFCM style",
    barColor: "#000000",
    textColor: "#fbbf24",
    buttonBgColor: "#fbbf24",
    buttonTextColor: "#000000",
  },
  {
    id: "ocean",
    name: "Ocean Blue",
    description: "Calm and trustworthy",
    barColor: "#1e40af",
    textColor: "#ffffff",
    buttonBgColor: "#ffffff",
    buttonTextColor: "#1e40af",
  },
  {
    id: "sunset",
    name: "Sunset Glow",
    description: "Warm and energetic",
    barColor: "#ea580c",
    textColor: "#ffffff",
    buttonBgColor: "#fef3c7",
    buttonTextColor: "#9a3412",
  },
  {
    id: "minimal",
    name: "Minimal Light",
    description: "Subtle and clean",
    barColor: "#f5f5f4",
    textColor: "#292524",
    buttonBgColor: "#292524",
    buttonTextColor: "#ffffff",
  },
  {
    id: "holiday",
    name: "Holiday Festive",
    description: "Seasonal celebrations",
    barColor: "#991b1b",
    textColor: "#ffffff",
    buttonBgColor: "#16a34a",
    buttonTextColor: "#ffffff",
  },
];
